app: Assessment-platform
service: Assessment-platform
frameworkVersion: '3'


plugins:
 - serverless-offline
 - serverless-aws-static-file-handler

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1


functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true

      - http:
          path: /{proxy}
          method: any
          cors:
            origins: 'https://assessment-platform-b630c.web.app'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true  # Set to true if you want to allow credentials (cookies, authorization headers) in CORS requests
            maxAge: 86400  #


  # - 'https://assessment-platform-b630c.web.app'
  #             - 'http://localhost:5173'